package com.chillzone.vanish;

import com.mojang.brigadier.Command;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents;
import net.luckperms.api.LuckPerms;
import net.luckperms.api.LuckPermsProvider;
import net.luckperms.api.model.user.User;
import net.minecraft.ChatFormatting;
import net.minecraft.commands.Commands;
import net.minecraft.network.chat.Component;
import net.minecraft.network.protocol.game.ClientboundAddEntityPacket;
import net.minecraft.network.protocol.game.ClientboundPlayerInfoRemovePacket;
import net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket;
import net.minecraft.network.protocol.game.ClientboundRemoveEntitiesPacket;
import net.minecraft.network.protocol.game.ClientboundTabListPacket;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.world.entity.EntityTypes;

import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.concurrent.ConcurrentHashMap;

public final class ChillZoneVanish implements ModInitializer {
    public static final String PERMISSION = "chillzonevanish.command.vanish";
    private static final Set<UUID> VANISHED = ConcurrentHashMap.newKeySet();
    // Unvanish is deliberately delayed for a few ticks. If /vanish is toggled
    // rapidly, the pending reveal is cancelled before any ADD_PLAYER/entity
    // packet is sent, preventing a one-frame TAB flash.
    private static final ConcurrentHashMap<UUID, Integer> PENDING_REVEAL = new ConcurrentHashMap<>();
    private static final int REVEAL_DELAY_TICKS = 10;

    // Remember the most recent header/footer packet generated by the server's TAB
    // system for each viewer. Vanish does not own the TAB design; it only rewrites
    // the visible player count inside the packet while preserving the rest.
    private static final Map<UUID, ClientboundTabListPacket> LAST_TAB_LIST = new ConcurrentHashMap<>();
    private static final Pattern PLAYER_COUNT = Pattern.compile(
        "(?i)(Players\\s*:\\s*)(\\d+)(\\s*/\\s*)(\\d+)"
    );

    @Override
    public void onInitialize() {
        CommandRegistrationCallback.EVENT.register((dispatcher, registryAccess, environment) ->
            dispatcher.register(Commands.literal("vanish")
                .requires(source -> source.getEntity() instanceof ServerPlayer p && hasPermission(p))
                .executes(ctx -> {
                    toggle(ctx.getSource().getPlayerOrException());
                    return Command.SINGLE_SUCCESS;
                }))
        );

        ServerPlayConnectionEvents.JOIN.register((handler, sender, server) ->
            server.execute(() -> {
                ServerPlayer joining = handler.getPlayer();
                for (UUID id : VANISHED) {
                    ServerPlayer hidden = server.getPlayerList().getPlayer(id);
                    if (hidden != null && hidden != joining) hideFrom(hidden, joining);
                }
            })
        );

        ServerPlayConnectionEvents.DISCONNECT.register((handler, server) -> {
            UUID id = handler.getPlayer().getUUID();
            VANISHED.remove(id);
            PENDING_REVEAL.remove(id);
            LAST_TAB_LIST.remove(id);
            // Run after the disconnect has finished so the visible count reflects
            // the remaining online players.
            server.execute(() -> refreshTabCounts(server));
        });

        // Re-assert vanish every server tick. This closes the brief TAB/entity
        // reappearance window caused by other mods or player-info refreshes.
        ServerTickEvents.END_SERVER_TICK.register(server -> {
            // Hidden wins over every refresh: remove TAB + tracked entity every tick.
            for (UUID id : VANISHED) {
                ServerPlayer hidden = server.getPlayerList().getPlayer(id);
                if (hidden == null) continue;
                for (ServerPlayer viewer : server.getPlayerList().getPlayers()) {
                    if (viewer != hidden) hideFrom(hidden, viewer);
                }
            }

            // Reveal only after the state has remained stable for the full delay.
            // A rapid second /vanish cancels this before showTo() can run.
            PENDING_REVEAL.replaceAll((id, ticks) -> ticks - 1);
            for (var entry : PENDING_REVEAL.entrySet()) {
                if (entry.getValue() > 0) continue;
                UUID id = entry.getKey();
                if (!PENDING_REVEAL.remove(id, entry.getValue())) continue;
                if (!VANISHED.remove(id)) continue;
                ServerPlayer shown = server.getPlayerList().getPlayer(id);
                if (shown == null) continue;
                for (ServerPlayer viewer : server.getPlayerList().getPlayers()) {
                    if (viewer != shown) showTo(shown, viewer);
                }
                broadcastFake(server, shown, true);
                refreshTabCounts(server);
                shown.sendSystemMessage(Component.literal("You are now visible."));
            }
        });
    }

    /**
     * Called by the packet mixin whenever another mod/plugin sends a TAB
     * header/footer packet. The original packet is remembered so vanish can
     * immediately refresh the count on toggle, then only the "Players: X/Y"
     * number is rewritten. The server-list/MOTD count is intentionally untouched.
     */
    public static ClientboundTabListPacket rewriteTabListPacket(ServerPlayer viewer, ClientboundTabListPacket packet) {
        if (viewer == null || packet == null) return packet;
        LAST_TAB_LIST.put(viewer.getUUID(), packet);

        MinecraftServer server = viewer.level().getServer();
        if (server == null) return packet;

        int visible = visiblePlayerCount(server);
        Component header = rewritePlayerCount(packet.header(), visible);
        Component footer = rewritePlayerCount(packet.footer(), visible);
        if (header == packet.header() && footer == packet.footer()) return packet;
        return new ClientboundTabListPacket(header, footer);
    }

    private static int visiblePlayerCount(MinecraftServer server) {
        int count = 0;
        for (ServerPlayer online : server.getPlayerList().getPlayers()) {
            if (!VANISHED.contains(online.getUUID())) count++;
        }
        return count;
    }

    private static void refreshTabCounts(MinecraftServer server) {
        for (ServerPlayer viewer : server.getPlayerList().getPlayers()) {
            ClientboundTabListPacket last = LAST_TAB_LIST.get(viewer.getUUID());
            if (last != null) viewer.connection.send(last);
        }
    }

    /**
     * Rebuild the flattened component while preserving each segment's effective
     * Style. This changes only the numeric online count and leaves the rest of
     * the TAB header/footer (colours, click/hover style, other lines) intact.
     */
    private static Component rewritePlayerCount(Component original, int visible) {
        if (original == null) return Component.empty();

        List<Component> flat = original.toFlatList();
        StringBuilder plain = new StringBuilder();
        for (Component part : flat) plain.append(part.getString());

        Matcher matcher = PLAYER_COUNT.matcher(plain);
        if (!matcher.find()) return original;

        int numberStart = matcher.start(2);
        int numberEnd = matcher.end(2);
        String replacement = Integer.toString(visible);

        MutableComponent rebuilt = Component.empty();
        int cursor = 0;
        boolean inserted = false;

        for (Component part : flat) {
            String text = part.getString();
            int partStart = cursor;
            int partEnd = cursor + text.length();

            if (partEnd <= numberStart || partStart >= numberEnd) {
                appendStyled(rebuilt, text, part);
            } else {
                if (partStart < numberStart) {
                    appendStyled(rebuilt, text.substring(0, numberStart - partStart), part);
                }

                if (!inserted) {
                    appendStyled(rebuilt, replacement, part);
                    inserted = true;
                }

                if (partEnd > numberEnd) {
                    appendStyled(rebuilt, text.substring(numberEnd - partStart), part);
                }
            }

            cursor = partEnd;
        }

        return inserted ? rebuilt : original;
    }

    private static void appendStyled(MutableComponent target, String text, Component styleSource) {
        if (text == null || text.isEmpty()) return;
        target.append(Component.literal(text).setStyle(styleSource.getStyle()));
    }

    private static boolean hasPermission(ServerPlayer player) {
        try {
            LuckPerms lp = LuckPermsProvider.get();
            User user = lp.getUserManager().getUser(player.getUUID());
            return user != null &&
                user.getCachedData().getPermissionData().checkPermission(PERMISSION).asBoolean();
        } catch (IllegalStateException ignored) {
            // Fail closed if LuckPerms is unavailable; avoids relying on removed 26.2 permission APIs.
            return false;
        }
    }

    private static void toggle(ServerPlayer player) {
        UUID id = player.getUUID();
        if (PENDING_REVEAL.remove(id) != null) {
            // Rapid vanish -> unvanish -> vanish: never reveal in between.
            VANISHED.add(id);
            MinecraftServer server = player.level().getServer();
            if (server != null) {
                for (ServerPlayer viewer : server.getPlayerList().getPlayers()) {
                    if (viewer != player) hideFrom(player, viewer);
                }
            }
            player.sendSystemMessage(Component.literal("Reveal cancelled. You remain vanished."));
        } else if (VANISHED.contains(id)) {
            unvanish(player);
        } else {
            vanish(player);
        }
    }

    private static void vanish(ServerPlayer player) {
        PENDING_REVEAL.remove(player.getUUID());
        VANISHED.add(player.getUUID());
        MinecraftServer server = player.level().getServer();
        if (server == null) return;

        for (ServerPlayer viewer : server.getPlayerList().getPlayers()) {
            if (viewer != player) hideFrom(player, viewer);
        }

        broadcastFake(server, player, false);
        refreshTabCounts(server);
        player.sendSystemMessage(Component.literal("You are now vanished."));
    }

    private static void unvanish(ServerPlayer player) {
        // Keep VANISHED set until the delayed reveal actually fires. This is the
        // key to preventing TAB/entity flashes during rapid toggling.
        PENDING_REVEAL.put(player.getUUID(), REVEAL_DELAY_TICKS);
        player.sendSystemMessage(Component.literal("Unvanishing..."));
    }

    private static void hideFrom(ServerPlayer hidden, ServerPlayer viewer) {
        viewer.connection.send(new ClientboundPlayerInfoRemovePacket(List.of(hidden.getUUID())));
        viewer.connection.send(new ClientboundRemoveEntitiesPacket(hidden.getId()));
    }

    private static void showTo(ServerPlayer shown, ServerPlayer viewer) {
        viewer.connection.send(ClientboundPlayerInfoUpdatePacket.createPlayerInitializing(List.of(shown)));
        viewer.connection.send(new ClientboundAddEntityPacket(
            shown.getId(),
            shown.getUUID(),
            shown.getX(), shown.getY(), shown.getZ(),
            shown.getXRot(), shown.getYRot(),
            EntityTypes.PLAYER,
            0,
            shown.getDeltaMovement(),
            shown.getYHeadRot()
        ));
    }

    private static void broadcastFake(MinecraftServer server, ServerPlayer player, boolean joined) {
        // Match Minecraft's normal join/leave message colour. The yellow style is
        // applied at the parent level so uncoloured name/text segments inherit it,
        // while any explicit LuckPerms prefix colours are preserved.
        Component message = Component.empty()
            .withStyle(ChatFormatting.YELLOW)
            .append(prefixedName(player))
            .append(Component.literal(joined ? " joined the game" : " left the game"));
        server.getPlayerList().broadcastSystemMessage(message, false);
    }

    private static Component prefixedName(ServerPlayer player) {
        String prefix = "";
        try {
            LuckPerms lp = LuckPermsProvider.get();
            User user = lp.getUserManager().getUser(player.getUUID());
            if (user != null && user.getCachedData().getMetaData().getPrefix() != null) {
                prefix = user.getCachedData().getMetaData().getPrefix();
            }
        } catch (IllegalStateException ignored) {}

        Component out = Component.empty();
        if (!prefix.isBlank()) {
            out = out.copy().append(LegacyText.parse(prefix));
            if (!prefix.endsWith(" ")) out = out.copy().append(Component.literal(" "));
        }
        return out.copy().append(player.getName());
    }
}
